In [ ]:
# Installs

In [2]:
# imports
import pandas as pd
import numpy as np

In [102]:
# Data Cleaning
df = pd.read_csv('adult.csv')
df.head(20)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K

In [105]:
# df.replace('?', pd.NA, inplace=True)

# Data cleaning for question marks (?)
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
df.replace('?', pd.NA, inplace=True)
df.dropna(inplace=True)

# Data cleaning for question marks (?)
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
df.replace('?', pd.NA, inplace=True)
df.dropna(inplace=True)

# df.info()
# df.head(40)

In [106]:
# Column cleaning
df.columns = df.columns.str.lower().str.replace('-', '_')

# Change datatype of the column to appropraite data types
categorical_cols = ['workclass', 'education', 'marital_status', 'occupation',
                    'relationship', 'race', 'gender', 'native_country', 'income']
for col in categorical_cols:
    df[col] = df[col].astype('string')

df['age'] = df['age'].astype(int)
df['hours_per_week'] = df['hours_per_week'].astype(int)


df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              30162 non-null  int64
 1   workclass        30162 non-null  string
 2   fnlwgt           30162 non-null  int64
 3   education        30162 non-null  string
 4   educational_num  30162 non-null  int64
 5   marital_status   30162 non-null  string
 6   occupation       30162 non-null  string
 7   relationship     30162 non-null  string
 8   race             30162 non-null  string
 9   gender           30162 non-null  string
 10  capital_gain     30162 non-null  int64
 11  capital_loss     30162 non-null  int64
 12  hours_per_week   30162 non-null  int64
 13  native_country   30162 non-null  string
 14  income           30162 non-null  string
dtypes: int64(6), string(9)
memory usage: 3.7 MB

In [107]:
# 1. How many men and women (sex feature) are represented in this dataset?
df['gender'].value_counts()

gender
Male      20380
Female     9782
Name: count, dtype: Int64

In [108]:
# 2. What is the average age (age feature) of women?
age_df = df[df['gender'] == 'Female']
age_df['age'].mean()

np.float64(36.8834594152525)

In [109]:
# 3. What is the percentage of German citizens (native-country feature)?
de_df = df[df['native_country']=='Germany']
len_ger = len(de_df)
len_tot = len(df)
result = round((len_ger / len_tot) * 100, 3)

print("The percentage is", result, "%")

The percentage is 0.424 %

In [110]:
# 4. What are the mean and standard deviation of age for those who earn more than
# 50K per year (salary feature) and those who earn less than 50K per year? 
# group = df[df['income'] == '<50K']

# print('Mean of population having >50K per year', round(group['age'].mean(), 3))

# print('Mean of population having >50K per year', round(group['age'].std(), 3))


# Second solution 
age_stats_by_income = df.groupby('income')['age'].agg(['mean', 'std'])
age_stats_by_income

            mean        std
income
<=50K   36.60806  13.464631
>50K    43.95911  10.269633

In [ ]:
# Test

In [111]:
# 5. Is it true that people who earn more than 50K have at least a high school
# education? (education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, 
# Masters or Doctorate feature)

df.groupby(['education', 'income'])['income'].agg(['count'])



# Define list of "high education" levels
high_education = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']

# Filter people who earn more than 50K
high_earners = df[df['income'] == '>50K']

# Find high earners who do NOT have high education
not_high_edu = high_earners[~high_earners['education'].isin(high_education)]

# Check how many such people exist
not_high_edu_count = len(not_high_edu)
total_high_earners = len(high_earners)

print("Number of people not having atleast Higer education" ,not_high_edu_count, "\nTotal Number having >50K:", total_high_earners)

print(round((not_high_edu_count / total_high_earners) * 100,2), "% of those not having higher education")

Number of people not having atleast Higer education 3178
Total Number having >50K: 7508
42.33 % of those not having higher education

In [112]:
# 6. Display age statistics for each race (race feature) and each gender (sex feature).
# Use groupby() and describe(). Find the maximum age of men 
# of Amer-Indian-Eskimo race.
df.head()

df.groupby(['race', 'gender'])['age'].describe()

race = df[(df['race'] == 'Amer-Indian-Eskimo') & (df['gender'] == 'Male')]['age'].max()
race

np.int64(71)

In [113]:
# 7. Among whom is the proportion of those who earn a lot (>50K) greater: married or
# single men (marital-status feature)? Consider as married those who have
# a marital-status starting with Married (Married-civ-spouse, Married-spouse-absent 
# or Married-AF-spouse), the rest are considered bachelors.

# married = ['Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse']
men = df[(df['gender'] == 'Male') & (df['income'] == '>50K')]
married_men = men[men['marital_status'].str.contains('Married')]
single_men = men[~men['marital_status'].str.contains('Married')]

m_ratio = len(married_men)
s_ratio = len(single_men)

print(m_ratio, s_ratio)




# Filter only male entries
men_df = df[df['gender'] == 'Male'].copy()

# Create a new column to label men as married or single
men_df['is_married'] = men_df['marital_status'].str.startswith('Married')

# Calculate proportions of >50K earners in each group
married_men = men_df[men_df['is_married']]
single_men = men_df[~men_df['is_married']]

married_high_income_ratio = (married_men['income'] == '>50K').mean()
single_high_income_ratio = (single_men['income'] == '>50K').mean()

married_high_income_ratio, single_high_income_ratio

# len()

5723 673

(np.float64(0.4479843444227006), np.float64(0.08849441157133466))

In [114]:
# 8. What is the maximum number of hours a person works per week
# (hours-per-week feature)? How many people work such a number of hours, and
# what is the percentage of those who earn a lot (>50K) among them?

max_hour = df['hours_per_week'].max()

num_of_people = len(df[df['hours_per_week'] == max_hour])

earn_alot = df[df['income'] == '>50K']
print("The percentage is", round(len(earn_alot) / len(df) * 100, 2), "%")

The percentage is 24.89 %

In [115]:
# 9. Count the average time of work (hours-per-week) for those who earn a little and a
# lot (salary) for each country (native-country). What will these be for Japan?
df.groupby(['income','native_country'])['hours_per_week'].agg(['mean'])
df[df['native_country'] == 'Japan'].groupby('income')['hours_per_week'].agg(['mean'])

             mean
income
<=50K   41.333333
>50K    48.086957

In [ ]:
# 10. Find out the total number of hours worked and mean salary as per different
# occupations.

df.groupby('occupation')['hours_per_week'].agg(['sum', 'mean'])

                      sum       mean
occupation
Adm-clerical       139766  37.561408
Armed-Forces          366  40.666667
Craft-repair       170461  42.298015
Exec-managerial    179508  44.966934
Farming-fishing     46474  46.990900
Handlers-cleaners   51131  37.874815
Machine-op-inspct   80030  40.707019
Other-service      111153  34.605542
Priv-house-serv      4690  32.797203
Prof-specialty     171110  42.374938
Protective-serv     27593  42.846273
Sales              146096  40.763393
Tech-support        36000  39.473684
Transport-moving    70190  44.650127

In [ ]:
# Test