In [4]:
%pip install pandas
%pip install numpy
%pip install openpyxl

Requirement already satisfied: pandas in c:\users\pieumeulrich\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pieumeulrich\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pieumeulrich\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pieumeulrich\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pieumeulrich\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pieumeulrich\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\pieumeulrich\appdata\local\programs\python\python312\lib\site-packages (2.2.4)
Note: you may need to restart the kernel to use updated packages.
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [6]:
# path='C:\\Users\\LENOVO\\Desktop\\NPOWER Materials\\Vancouver resources\\Course 7\\Week 1\GoodBelly-DataSet-Regression.xlsx'
df=pd.read_excel("GoodBelly-DataSet.xlsx", 'Real Data')
df.head(20)

,Date,Region,Store,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
0,2010-05-04,FL,Biscayne (aka Aventura),150.702088,4.390000,0,0,0,0,0,1,0
1,2010-05-11,FL,Biscayne (aka Aventura),197.403797,3.997692,0,0,0,0,0,1,0
2,2010-05-18,FL,Biscayne (aka Aventura),235.106172,3.809231,0,0,0,0,0,1,0
3,2010-05-25,FL,Biscayne (aka Aventura),226.692427,3.835000,0,0,0,0,0,1,0
4,2010-06-01,FL,Biscayne (aka Aventura),257.688151,3.902500,0,0,0,0,0,1,0
5,2010-06-08,FL,Biscayne (aka Aventura),132.957190,4.497692,0,0,0,0,0,1,0
6,2010-06-15,FL,Biscayne (aka Aventura),221.889969,4.116667,0,0,0,0,0,1,0
7,2010-06-22,FL,Biscayne (aka Aventura),245.881356,4.116667,0,0,0,0,0,1,0
8,2010-06-29,FL,Biscayne (aka Aventura),156.102535,4.116667,0,0,0,0,0,4,0
9,2010-07-06,FL,Biscayne (aka Aventura),200.103966,3.747333,0,0,0,0,0,1,0
10,2010-07-13,FL,Biscayne (aka Aventura),128.396003,4.012500,0,0,0,0,0,1,0
11,2010-05-04,FL,Boca Raton,142.778210,4.390000,0,0,0,0,0,0,4
12,2010-05-11,FL,Boca Raton,237.544554,4.235455,0,0,0,0,0,0,4
13,2010-05-18,FL,Boca Raton,141.533297,3.809231,0,0,0,0,0,0,4
14,2010-05-25,FL,Boca Raton,158.073949,3.809231,0,0,0,0,0,0,4
15,2010-06-01,FL,Boca Raton,255.117743,4.055625,0,0,0,0,0,0,4
16,2010-06-08,FL,Boca Raton,129.793627,4.383333,0,0,0,0,0,0,4
17,2010-06-15,FL,Boca Raton,137.764285,4.358750,0,0,0,0,0,0,4
18,2010-06-22,FL,Boca Raton,306.793819,4.358750,0,0,0,0,0,0,4
19,2010-06-29,FL,Boca Raton,103.319023,4.358750,0,0,0,0,0,0,4

In [ ]:
# 1. Find how many records this data frame has;
len(df)

1386

In [ ]:
# 2. How many elements are there?
print("Number of elements:")
df.size

Number of elements:

16632

In [ ]:
# 3. What are the column names?
df.columns

Index(['Date', 'Region', 'Store', 'Units Sold', 'Average Retail Price',
       'Sales Rep', 'Endcap', 'Demo', 'Demo1-3', 'Demo4-5', 'Natural',
       'Fitness'],
      dtype='object')

In [ ]:
# 4. What types of columns do we have in this dataframe?
df.dtypes

Date                    datetime64[ns]
Region                          object
Store                           object
Units Sold                     float64
Average Retail Price           float64
Sales Rep                        int64
Endcap                           int64
Demo                             int64
Demo1-3                          int64
Demo4-5                          int64
Natural                          int64
Fitness                          int64
dtype: object

In [9]:
# 5. Give the summary for thenumeric columns in the dataset
df.describe()

,Date,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
count,1386,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000
mean,2010-06-08 00:00:00,253.820718,4.107093,0.549784,0.038240,0.058442,0.156566,0.075758,1.448773,2.476190
min,2010-05-04 00:00:00,47.559852,2.889286,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2010-05-18 00:00:00,189.995471,3.775714,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,2010-06-08 00:00:00,236.735266,4.096667,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000
75%,2010-06-29 00:00:00,295.804391,4.425067,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,4.000000
max,2010-07-13 00:00:00,1041.200256,6.251538,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,5.000000
std,NaN,110.998731,0.463828,0.497695,0.191843,0.234661,0.363522,0.264705,0.975092,1.592789

In [8]:
# 6. Calculate standard deviation for all numeric columns;
df.iloc[:,3:].std(ddof=0)

Units Sold              110.958681
Average Retail Price      0.463661
Sales Rep                 0.497515
Endcap                    0.191774
Demo                      0.234577
Demo1-3                   0.363391
Demo4-5                   0.264610
Natural                   0.974740
Fitness                   1.592215
dtype: float64

In [7]:
# 7. What are the mean values of the first 50 records in the dataset? Hint:
# usehead() method to subset the first 50 records and then calculate the
# mean

df.head(50).iloc[:,3:].mean()

Units Sold              186.280727
Average Retail Price      4.128036
Sales Rep                 0.000000
Endcap                    0.100000
Demo                      0.000000
Demo1-3                   0.000000
Demo4-5                   0.040000
Natural                   1.300000
Fitness                   1.560000
dtype: float64