In [ ]:
import pandas as pd
# 1) Download cities.csv in C7W1 Activity folder 

# 2) Import the CSV in a dataframe

df = pd.read_csv('cities.csv')

df

:

In [8]:
# 3) Add a column to the dataframe

df['new_column'] = None
df

,LatD,"""LatM""","""LatS""","""NS""","""LonD""","""LonM""","""LonS""","""EW""","""City""","""State""",new_column
0,41,5,59,"""N""",80,39,0,"""W""","""Youngstown""",OH,None
1,42,52,48,"""N""",97,23,23,"""W""","""Yankton""",SD,None
2,46,35,59,"""N""",120,30,36,"""W""","""Yakima""",WA,None
3,42,16,12,"""N""",71,48,0,"""W""","""Worcester""",MA,None
4,43,37,48,"""N""",89,46,11,"""W""","""Wisconsin Dells""",WI,None
...,...,...,...,...,...,...,...,...,...,...,...
123,39,31,12,"""N""",119,48,35,"""W""","""Reno""",NV,None
124,50,25,11,"""N""",104,39,0,"""W""","""Regina""",SA,None
125,40,10,48,"""N""",122,14,23,"""W""","""Red Bluff""",CA,None
126,40,19,48,"""N""",75,55,48,"""W""","""Reading""",PA,None
127,41,9,35,"""N""",81,14,23,"""W""","""Ravenna""",OH,None

In [10]:
# 4) Perform describe and info on dataframe
df.describe()
# df.info()

             LatD      "LatM"      "LatS"      "LonD"      "LonM"      "LonS"
count  128.000000  128.000000  128.000000  128.000000  128.000000  128.000000
mean    38.820312   30.765625   27.492188   93.250000   27.742188   26.960938
std      5.200596   16.426158   18.977814   15.466499   16.927937   18.727807
min     26.000000    1.000000    0.000000   71.000000    0.000000    0.000000
25%     35.000000   16.000000   11.000000   80.000000   14.000000   11.000000
50%     39.000000   31.000000   24.000000   89.500000   26.500000   23.500000
75%     42.250000   45.000000   47.000000  103.250000   40.250000   47.000000
max     50.000000   59.000000   59.000000  123.000000   58.000000   59.000000

In [11]:
# 5) Export and save this data as cities1.csv
df.to_csv('cities1.csv')

In [19]:
!pip install xlrd
!pip list
# 1) Download CarSalesByModelStart.xlsx in C7W1 Activity folder 
# 2) Import xlsx in a dataframe

Package               Version
--------------------- -----------
attrs                 22.2.0
backcall              0.2.0
beautifulsoup4        4.12.3
bleach                4.1.0
bs4                   0.0.2
certifi               2025.1.31
charset-normalizer    2.0.12
colorama              0.4.5
cycler                0.11.0
decorator             5.1.1
docutils              0.18.1
entrypoints           0.4
fire                  0.1.2
idna                  3.10
importlib-metadata    4.8.3
importlib-resources   5.4.0
ipykernel             5.5.6
ipython               7.16.3
ipython-genutils      0.2.0
jedi                  0.17.2
jsonschema            3.2.0
jupyter-client        7.1.2
jupyter-core          4.9.2
keyring               23.4.1
kiwisolver            1.3.1
matplot               0.1.9
matplotlib            3.3.4
nbformat              5.1.3
nest-asyncio          1.6.0
numpy                 1.19.5
packaging             21.3
pandas                1.1.5
parso                 0.7.1
peewee                2.8.8
pickleshare           0.7.5
Pillow                8.4.0
pip                   21.3.1
pkginfo               1.10.0
prompt-toolkit        3.0.36
Pygments              2.14.0
pyloco                0.0.139
pyparsing             3.1.4
pyrsistent            0.18.0
python-dateutil       2.9.0.post0
pytz                  2025.1
pywin32               305
pywin32-ctypes        0.2.3
pyzmq                 25.1.2
readme-renderer       34.0
requests              2.27.1
requests-toolbelt     1.0.0
rfc3986               1.5.0
setuptools            40.6.2
SimpleWebSocketServer 0.1.2
six                   1.17.0
soupsieve             2.3.2.post1
tornado               6.1
tqdm                  4.64.1
traitlets             4.3.3
twine                 3.8.0
typing                3.7.4.3
typing_extensions     4.1.1
urllib3               1.26.20
ushlex                0.99.1
wcwidth               0.2.13
webencodings          0.5.1
websocket-client      1.3.1
zipp                  3.6.0

In [22]:
df_ex = pd.read_excel('CarSalesByModelStart.xlsx')
df_ex

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

In [ ]:
# 1) Download Jay.json in C7W1 Activity folder 
# 2) Import the Json in dataframe
# 3) Add a column to the dataframe
# 4) Perform describe and info on dataframe 
# 5) Export and save this data as Jay1.json